### ISSUE TITLE
golang 语言学习

### ISSUE THREAD

**Issue by weiweimilk** [mark-20202/golang-#1]
1、先学习下golang官网的例子哈
https://golang.org/#

2、然后看下这个文档：
https://golang.org/doc/

学习的时候，要在自己的机器上把代码写下来，并运行，并把代码提交到github里；

PS： 以后你会学习很多开源软件，要学会看官方文档

**Comment by mark-20202** [comment]
好的

**Comment by weiweimilk** [comment]
close

**Comment by weiweimilk** [comment]
close
